### ISSUE TITLE
Unexpected return code 127

### ISSUE THREAD

**Issue by martapavelka** [martapavelka/scpc#23]
Both UM instances of scpc and scpc-dev result into following `Runtime Exception: Unexpected return code 127.` for any input/property (even default).

Reproducing the error:

1) Open any of the following links:
https://www.math.miami.edu/~pavelka/scpc/
https://www.math.miami.edu/~pavelka/scpc-dev/
2) Click submit.
3) See the error message.

**Comment by petrzpav** [comment]
It is probably server issue because I'am not able to connect to the server with given credentials. It looks like the server has been moved / reinstalled or something like this. Please contact your server administrator and ask him to give us new login and password. Then we will see.

**Comment by martapavelka** [comment]
Just emailed him!

**Comment by jiripavelka** [comment]
Remind Jeff that you’re also unable to connect using provided credentials nor authorized ssh keys. And cc Bruno pls.

**Comment by petrzpav** [comment]
I just looked at the server and someone -- probably Jeff fixed the problem. So you can say thanks to him :-)
