### ISSUE TITLE
Colab code failing

### ISSUE THREAD

**Issue by martapavelka** [martapavelka/scpc#24]
Google Colab code generates the following exception for default values:

```
An exception has occurred, use %tb to see the full traceback.

SystemExit: 3
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2890: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

1) Open the following link
https://colab.research.google.com/github/martapavelka/scpc/blob/dev/scpc.ipynb
2) Run first three code cells
3) Read the error

**Comment by petrzpav** [comment]
When check pass then script prints matrix (try run next cell) otherwise script returns `SystemExit: 3`. So it is expected behavior.
